//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDWithAjaxJQuery
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerWiseBonusRate
    {
        public int Id { get; set; }
        public long CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> BonusRate { get; set; }
        public Nullable<System.DateTime> BonusDate { get; set; }
    }
}
